language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-27.0.3
    # The SDK version used to compile your project
    - android-25
before_install:
  - sudo apt-get install ant
install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"