package com.github.sylvain121.SimpleRemoteDesktop.player.keyboard;

public class LinuxKeyCode {
    public final static int KEY_RESERVED = 0;
    public final static int KEY_ESC = 1;
    public final static int KEY_1 = 2;
    public final static int KEY_2 = 3;
    public final static int KEY_3 = 4;
    public final static int KEY_4 = 5;
    public final static int KEY_5 = 6;
    public final static int KEY_6 = 7;
    public final static int KEY_7 = 8;
    public final static int KEY_8 = 9;
    public final static int KEY_9 = 10;
    public final static int KEY_0 = 11;
    public final static int KEY_MINUS = 12;
    public final static int KEY_EQUAL = 13;
    public final static int KEY_BACKSPACE = 14;
    public final static int KEY_TAB = 15;
    public final static int KEY_Q = 16;
    public final static int KEY_W = 17;
    public final static int KEY_E = 18;
    public final static int KEY_R = 19;
    public final static int KEY_T = 20;
    public final static int KEY_Y = 21;
    public final static int KEY_U = 22;
    public final static int KEY_I = 23;
    public final static int KEY_O = 24;
    public final static int KEY_P = 25;
    public final static int KEY_LEFTBRACE = 26;
    public final static int KEY_RIGHTBRACE = 27;
    public final static int KEY_ENTER = 28;
    public final static int KEY_LEFTCTRL = 29;
    public final static int KEY_A = 30;
    public final static int KEY_S = 31;
    public final static int KEY_D = 32;
    public final static int KEY_F = 33;
    public final static int KEY_G = 34;
    public final static int KEY_H = 35;
    public final static int KEY_J = 36;
    public final static int KEY_K = 37;
    public final static int KEY_L = 38;
    public final static int KEY_SEMICOLON = 39;
    public final static int KEY_APOSTROPHE = 40;
    public final static int KEY_GRAVE = 41;
    public final static int KEY_LEFTSHIFT = 42;
    public final static int KEY_BACKSLASH = 43;
    public final static int KEY_Z = 44;
    public final static int KEY_X = 45;
    public final static int KEY_C = 46;
    public final static int KEY_V = 47;
    public final static int KEY_B = 48;
    public final static int KEY_N = 49;
    public final static int KEY_M = 50;
    public final static int KEY_COMMA = 51;
    public final static int KEY_DOT = 52;
    public final static int KEY_SLASH = 53;
    public final static int KEY_RIGHTSHIFT = 54;
    public final static int KEY_KPASTERISK = 55;
    public final static int KEY_LEFTALT = 56;
    public final static int KEY_SPACE = 57;
    public final static int KEY_CAPSLOCK = 58;
    public final static int KEY_F1 = 59;
    public final static int KEY_F2 = 60;
    public final static int KEY_F3 = 61;
    public final static int KEY_F4 = 62;
    public final static int KEY_F5 = 63;
    public final static int KEY_F6 = 64;
    public final static int KEY_F7 = 65;
    public final static int KEY_F8 = 66;
    public final static int KEY_F9 = 67;
    public final static int KEY_F10 = 68;
    public final static int KEY_NUMLOCK = 69;
    public final static int KEY_SCROLLLOCK = 70;
    public final static int KEY_KP7 = 71;
    public final static int KEY_KP8 = 72;
    public final static int KEY_KP9 = 73;
    public final static int KEY_KPMINUS = 74;
    public final static int KEY_KP4 = 75;
    public final static int KEY_KP5 = 76;
    public final static int KEY_KP6 = 77;
    public final static int KEY_KPPLUS = 78;
    public final static int KEY_KP1 = 79;
    public final static int KEY_KP2 = 80;
    public final static int KEY_KP3 = 81;
    public final static int KEY_KP0 = 82;
    public final static int KEY_KPDOT = 83;

    public final static int KEY_ZENKAKUHANKAKU = 85;
    public final static int KEY_102ND = 86;
    public final static int KEY_F11 = 87;
    public final static int KEY_F12 = 88;
    public final static int KEY_RO = 89;
    public final static int KEY_KATAKANA = 90;
    public final static int KEY_HIRAGANA = 91;
    public final static int KEY_HENKAN = 92;
    public final static int KEY_KATAKANAHIRAGANA = 93;
    public final static int KEY_MUHENKAN = 94;
    public final static int KEY_KPJPCOMMA = 95;
    public final static int KEY_KPENTER = 96;
    public final static int KEY_RIGHTCTRL = 97;
    public final static int KEY_KPSLASH = 98;
    public final static int KEY_SYSRQ = 99;
    public final static int KEY_RIGHTALT = 100;
    public final static int KEY_LINEFEED = 101;
    public final static int KEY_HOME = 102;
    public final static int KEY_UP = 103;
    public final static int KEY_PAGEUP = 104;
    public final static int KEY_LEFT = 105;
    public final static int KEY_RIGHT = 106;
    public final static int KEY_END = 107;
    public final static int KEY_DOWN = 108;
    public final static int KEY_PAGEDOWN = 109;
    public final static int KEY_INSERT = 110;
    public final static int KEY_DELETE = 111;
    public final static int KEY_MACRO = 112;
    public final static int KEY_MUTE = 113;
    public final static int KEY_VOLUMEDOWN = 114;
    public final static int KEY_VOLUMEUP = 115;
    public final static int KEY_POWER = 116;    /* SC System Power Down */
    public final static int KEY_KPEQUAL = 117;
    public final static int KEY_KPPLUSMINUS = 118;
    public final static int KEY_PAUSE = 119;
    public final static int KEY_SCALE = 120;    /* AL Compiz Scale (Expose) */

    public final static int KEY_KPCOMMA = 121;
    public final static int KEY_HANGEUL = 122;
    public final static int KEY_HANGUEL = KEY_HANGEUL;
    public final static int KEY_HANJA = 123;
    public final static int KEY_YEN = 124;
    public final static int KEY_LEFTMETA = 125;
    public final static int KEY_RIGHTMETA = 126;
    public final static int KEY_COMPOSE = 127;

    public final static int KEY_STOP = 128;/* AC Stop */
    public final static int KEY_AGAIN = 129;
    public final static int KEY_PROPS = 130;/* AC Properties */
    public final static int KEY_UNDO = 131;/* AC Undo */
    public final static int KEY_FRONT = 132;
    public final static int KEY_COPY = 133;/* AC Copy */
    public final static int KEY_OPEN = 134;    /* AC Open */
    public final static int KEY_PASTE = 135;/* AC Paste */
    public final static int KEY_FIND = 136;/* AC Search */
    public final static int KEY_CUT = 137;    /* AC Cut */
    public final static int KEY_HELP = 138;    /* AL Integrated Help Center */
    public final static int KEY_MENU = 139;    /* Menu (show menu) */
    public final static int KEY_CALC = 140;/* AL Calculator */
    public final static int KEY_SETUP = 141;
    public final static int KEY_SLEEP = 142;    /* SC System Sleep */
    public final static int KEY_WAKEUP = 143;/* System Wake Up */
    public final static int KEY_FILE = 144;    /* AL Local Machine Browser */
    public final static int KEY_SENDFILE = 145;
    public final static int KEY_DELETEFILE = 146;
    public final static int KEY_XFER = 147;
    public final static int KEY_PROG1 = 148;
    public final static int KEY_PROG2 = 149;
    public final static int KEY_WWW = 150;/* AL Internet Browser */
    public final static int KEY_MSDOS = 151;
    public final static int KEY_COFFEE = 152;    /* AL Terminal Lock/Screensaver */
    public final static int KEY_SCREENLOCK = KEY_COFFEE;
    public final static int KEY_ROTATE_DISPLAY = 153;    /* Display orientation for e.g. tablets */
    public final static int KEY_DIRECTION = KEY_ROTATE_DISPLAY;
    public final static int KEY_CYCLEWINDOWS = 154;
    public final static int KEY_MAIL = 155;
    public final static int KEY_BOOKMARKS = 156;/* AC Bookmarks */
    public final static int KEY_COMPUTER = 157;
    public final static int KEY_BACK = 158;/* AC Back */
    public final static int KEY_FORWARD = 159;/* AC Forward */
    public final static int KEY_CLOSECD = 160;
    public final static int KEY_EJECTCD = 161;
    public final static int KEY_EJECTCLOSECD = 162;
    public final static int KEY_NEXTSONG = 163;
    public final static int KEY_PLAYPAUSE = 164;
    public final static int KEY_PREVIOUSSONG = 165;
    public final static int KEY_STOPCD = 166;
    public final static int KEY_RECORD = 167;
    public final static int KEY_REWIND = 168;
    public final static int KEY_PHONE = 169;    /* Media Select Telephone */
    public final static int KEY_ISO = 170;
    public final static int KEY_CONFIG = 171;    /* AL Consumer Control Configuration */
    public final static int KEY_HOMEPAGE = 172;    /* AC Home */
    public final static int KEY_REFRESH = 173;    /* AC Refresh */
    public final static int KEY_EXIT = 174;    /* AC Exit */
    public final static int KEY_MOVE = 175;
    public final static int KEY_EDIT = 176;
    public final static int KEY_SCROLLUP = 177;
    public final static int KEY_SCROLLDOWN = 178;
    public final static int KEY_KPLEFTPAREN = 179;
    public final static int KEY_KPRIGHTPAREN = 180;
    public final static int KEY_NEW = 181;    /* AC New */
    public final static int KEY_REDO = 182;/* AC Redo/Repeat */

    public final static int KEY_F13 = 183;
    public final static int KEY_F14 = 184;
    public final static int KEY_F15 = 185;
    public final static int KEY_F16 = 186;
    public final static int KEY_F17 = 187;
    public final static int KEY_F18 = 188;
    public final static int KEY_F19 = 189;
    public final static int KEY_F20 = 190;
    public final static int KEY_F21 = 191;
    public final static int KEY_F22 = 192;
    public final static int KEY_F23 = 193;
    public final static int KEY_F24 = 194;

    public final static int KEY_PLAYCD = 200;
    public final static int KEY_PAUSECD = 201;
    public final static int KEY_PROG3 = 202;
    public final static int KEY_PROG4 = 203;
    public final static int KEY_DASHBOARD = 204;    /* AL Dashboard */
    public final static int KEY_SUSPEND = 205;
    public final static int KEY_CLOSE = 206;    /* AC Close */
    public final static int KEY_PLAY = 207;
    public final static int KEY_FASTFORWARD = 208;
    public final static int KEY_BASSBOOST = 209;
    public final static int KEY_PRINT = 210;/* AC Print */
    public final static int KEY_HP = 211;
    public final static int KEY_CAMERA = 212;
    public final static int KEY_SOUND = 213;
    public final static int KEY_QUESTION = 214;
    public final static int KEY_EMAIL = 215;
    public final static int KEY_CHAT = 216;
    public final static int KEY_SEARCH = 217;
    public final static int KEY_CONNECT = 218;
    public final static int KEY_FINANCE = 219;    /* AL Checkbook/Finance */
    public final static int KEY_SPORT = 220;
    public final static int KEY_SHOP = 221;
    public final static int KEY_ALTERASE = 222;
    public final static int KEY_CANCEL = 223;    /* AC Cancel */
    public final static int KEY_BRIGHTNESSDOWN = 224;
    public final static int KEY_BRIGHTNESSUP = 225;
    public final static int KEY_MEDIA = 226;

    public final static int KEY_SWITCHVIDEOMODE = 227;/* Cycle between available video
					   outputs (Monitor/LCD/TV-out/etc) */
    public final static int KEY_KBDILLUMTOGGLE = 228;
    public final static int KEY_KBDILLUMDOWN = 229;
    public final static int KEY_KBDILLUMUP = 230;

    public final static int KEY_SEND = 231;/* AC Send */
    public final static int KEY_REPLY = 232;/* AC Reply */
    public final static int KEY_FORWARDMAIL = 233;    /* AC Forward Msg */
    public final static int KEY_SAVE = 234;/* AC Save */
    public final static int KEY_DOCUMENTS = 235;

    public final static int KEY_BATTERY = 236;

    public final static int KEY_BLUETOOTH = 237;
    public final static int KEY_WLAN = 238;
    public final static int KEY_UWB = 239;

    public final static int KEY_UNKNOWN = 240;

    public final static int KEY_VIDEO_NEXT = 241;/* drive next video source */
    public final static int KEY_VIDEO_PREV = 242;    /* drive previous video source */
    public final static int KEY_BRIGHTNESS_CYCLE = 243;    /* brightness up, after max is min */
    public final static int KEY_BRIGHTNESS_AUTO = 244;	/* Set Auto Brightness: manual
					  brightness control is off,
					  rely on ambient */
    public final static int KEY_BRIGHTNESS_ZERO = KEY_BRIGHTNESS_AUTO;
    public final static int KEY_DISPLAY_OFF = 245;    /* display device to off state */

    public final static int KEY_WWAN = 246;    /* Wireless WAN (LTE, UMTS, GSM, etc.) */
    public final static int KEY_WIMAX = KEY_WWAN;
    public final static int KEY_RFKILL = 247;    /* Key that controls all radios */

    public final static int KEY_MICMUTE = 248;    /* Mute / unmute the microphone */
}
